
domain: CitizenDeeJay.github.io 

title: CitizenDeeJay
email: deejay@dofddesign.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey!
url: https://CitizenDeeJay.github.io 
baseurl: "/site" # the subpath of your site, e.g. /blog
twitter_username: citizen_deejay
github_username:  citizendeejay

# Build settings
theme: minima
plugins:
  - jekyll-feed
